services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: unless-stopped
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
    ports:
      - "10086:10086"
