services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: unless-stopped
    command: run -c /etc/v2ray/config.json
    volumes:
      - ./config.json:/etc/v2ray/config.json:ro
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
  softether-server:
    image: siomiz/softethervpn
    cap_add:
      - NET_ADMIN
    ports:
      # L2TP/IPsec
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/udp
      # OpenVPN互換 & SoftEther
      - 1194:1194/udp
      - 443:443/tcp
      - 992:992/tcp
      # 管理/互換用（既存）
      - 5555:5555/tcp
    container_name: softether-server
    environment:
      - USERNAME=${VPN_USER}
      - PASSWORD=${VPN_PASSWORD}
      - SPW=${VPN_SERVER_PASSWORD}
      - PSK=${VPN_PSK}
      - HPW=${VPN_HUB_PASSWORD}
