services:
  v2ray:
    image: v2fly/v2fly-core
    command: ["run", "-c", "/etc/v2ray/config.json"]
    restart: always
    expose:
      - "443"
    volumes:
      - ./configs/v2ray/config.json:/etc/v2ray/config.json:ro

  caddy:
    image: caddy:2.8-alpine
    restart: always
    depends_on:
      - v2ray
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./web:/srv/web:ro
