version: '3'
services:
  web:
    image: caddy:2
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./configs/Caddyfile:/etc/caddy/Caddyfile:ro
        - ./web:/srv/web:ro
        - $HOME/.caddy:/data:rw
    depends_on:
      - v2ray
  v2ray:
    image: v2fly/v2fly-core
    command: ["run", "-c", "/etc/v2ray/config.json"]
    restart: always
    volumes:
        - ./configs/v2ray/config.json:/etc/v2ray/config.json:ro
