version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core
    command: ["run", "-c", "/etc/v2ray/config.json"]
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./configs/v2ray/config.json:/etc/v2ray/config.json:ro
