version: '3'
services:
  web:
    image: abiosoft/caddy
    platform: linux/amd64
    restart: always
    environment:
        - CADDY_TELEMETRY=off
        - CADDY_DISABLE_TELEMETRY=1
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./configs/Caddyfile:/etc/Caddyfile:ro
        - ./web:/srv/web:ro
        - $HOME/.caddy:/root/.caddy:rw
    links:
      - v2ray
  v2ray:
    image: v2fly/v2fly-core
    command: ["run", "-c", "/etc/v2ray/config.json"]
    restart: always
    expose:
        - "1443"
    volumes:
        - ./configs/v2ray/config.json:/etc/v2ray/config.json:ro
